services:
  python-producer:
    build:
      context: "./python service"
      dockerfile: Dockerfile
    container_name: python_producer
    restart: on-failure
    depends_on:
      - broker
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=broker:9092

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\"'" ]
      interval: 10s
      timeout: 5s
      retries: 12

  kib:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kib
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - "5601:5601"
    depends_on:
      es:
        condition: service_healthy

  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_CLUSTER_ID: '4L6g3nShT-eMCAabc1234g'

  consumer-app:
    build:
      context: "./csharp service/csharpservice/csharpconsumer"
      dockerfile: Dockerfile
    container_name: csharp_kafka_consumer
    restart: on-failure
    depends_on:
      es:
        condition: service_healthy
      broker:
        condition: service_started
    environment:
      - ElasticsearchSettings__Url=http://es:9200
      - ElasticsearchSettings__IndexName=processed_records
      - KafkaSettings__BootstrapServers=broker:9092
      - KafkaSettings__Topic=raw-data-first
      - KafkaSettings__GroupId=report-consumer-group-v5
  report-api:
    build:
      context: "./csharp service/csharpservice/ReportApi"
      dockerfile: Dockerfile
    container_name: csharp_report_api
    ports:
      - "8080:8080"
    environment:
      - ElasticsearchSettings__Url=http://es:9200
      - ElasticsearchSettings__IndexName=processed_records
    depends_on:
      es:
        condition: service_healthy

volumes:
  mongo_data: